### ISSUE TITLE
3.4 Training the model

### ISSUE THREAD

**Issue by huangmingxi** [rstraver/sanefalcon#5]
Hi，
I have gotten the training profiles (upstreamProfs.csv;downstreamProfs.csv) for each traning data set, should I use "cat" to combine them to only one training data set ? And my upstreamProfs.csv is in this format(figure 1).  Anything wrong with it ?
![image](https://user-images.githubusercontent.com/29935612/41829190-ebf34bde-786b-11e8-9530-52b12e6f6a30.png)

while I am going to run step3.4--Training the model , I am confusing about the trainNucl , which file should I pick ? upstreamProfs.csv or downstreamProfs.csv or both ?
![image](https://user-images.githubusercontent.com/29935612/41829294-7a855a5e-786c-11e8-82a3-39ee616b4e34.png)

I hope you can share the example file and shell script for this step,it maybe more easy to understand~ : )

Thanks in advance.

**Comment by rstraver** [comment]
Hi, thanks for your interest.

You should combine those two (upstream and downstream), as stated in the paragraph just before 3.4:

> At this point, I do not have a seperate script to combine the upstream and downstream profiles. Instead just open them in a spreadsheet tool, sort them both by file name so their orders are aligned and reverse the upstream profile (left most value must become rightmost etc), then stitch the two together by putting the downstream profiles after the upstream profiles.

Does that answer your question?

**Comment by huangmingxi** [comment]
thanks for your quick answer. @rstraver 

I have combine the upstream & downstream profile (reversed the upstream file; stitched the downstream file ;deleted one of the same column in the middle ),but I still get the same error as before.

this is my combined profiles files format:
![image](https://user-images.githubusercontent.com/29935612/42153339-670a40e4-7e15-11e8-9527-044f8f57f327.png)
my reference file :
![image](https://user-images.githubusercontent.com/29935612/42153484-d27b1038-7e15-11e8-8eca-20bb8f359e73.png)

shell script :
time python sanefalcon-master/predictor.py  test.csv   a_train.reference  FF_a

the error I got:
Traceback (most recent call last):
  File "sanefalcon-master/predictor.py", line 509, in <module>
    main()
  File "sanefalcon-master/predictor.py", line 349, in main
    samples,coverages = loadNuclFile(argv[1])
  File "sanefalcon-master/predictor.py", line 47, in loadNuclFile
    values=[float(x) for x in splitLine[int(sys.argv[6]):int(sys.argv[7])]]
IndexError: list index out of range

- Training stage:
- Training stage:
- Training stage:
0 samples overlap
0 samples noOverlap
- Training stage:

I probably made a mistake somewhere ?

Thanks.

**Comment by dprat** [comment]
Hi, 
i'm actually having an issue here too, thing is that i think there's a problem with argv[6] and argv[7] since these 2 arguments (from what i understand in the readme) are optional, but are actually needed in the script and here in your command line you don't give these 2 arguments, that's why you get the error message "IndexError: list index out of range" i'm trying to fix this error.
But i need to know what we are supposed to calculate with :
`values=[float(x) for x in splitLine[int(sys.argv[6]):int(sys.argv[7])]] `

Looks like argv[6] and argv[7] are 2 values
I haven't found anything in the readme

**Comment by rstraver** [comment]
Ah, that one is haunting me again... Sorry I should add that detail to the readme or just get rid of it. Basically those numbers want to know the start and end positions of the region you actually want to take into account in the nucleosome profiles you provided. Try running the script with a 1 and -1 at the end (start at first column that contains a value rather than the sample name, and end at the last position in the list). That should take the whole profile into account.

**Comment by ghost** [comment]
Hi @rstraver,

How to create reference file for this step?
**predictor.py test.csv a_train.reference FF_a**

please help me with this.

**Comment by rstraver** [comment]
@binfo2018 could you open predictor.py and change line 47 from:
```
	values=[float(x) for x in splitLine[int(sys.argv[6]):int(sys.argv[7])]]
```

to:
```
	values=[float(x) for x in splitLine[1:]]
```

and try again?

**Comment by smruti241** [comment]
> Hi @rstraver,
> 
> How to create reference file for this step?
> **predictor.py test.csv a_train.reference FF_a**
> 
> please help me with this.

hii @huangmingxi how did you create reference file? Please tell me
